# Generated by Django 4.2.4 on 2023-08-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("gar", "0002_veiculo_foto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="veiculo",
            options={"verbose_name": "Veiculo"},
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="marca",
        ),
        migrations.AddField(
            model_name="modelo",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modelo",
                to="gar.categoria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veiculo",
            name="descrição",
            field=models.CharField(default=1, max_length=99),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="foto",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="foto",
            field=models.ManyToManyField(related_name="Veiculo", to="uploader.image"),
        ),
    ]
