# Generated by Django 4.1.7 on 2023-03-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gar', '0002_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
