# Generated by Django 4.1.7 on 2023-04-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gar', '0004_acessório_cor_veiculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acessório',
            new_name='Acessorio',
        ),
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name_plural': 'Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
    ]
