# Generated by Django 4.1.7 on 2023-04-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0005_rename_acessório_acessorio_alter_acessorio_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="modelo",
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=70)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelo",
                        to="gar.marca",
                    ),
                ),
            ],
        ),
    ]
