# Generated by Django 4.1.7 on 2023-04-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gar", "0006_remove_veiculo_modelo_modelo"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculos",
                to="gar.modelo",
            ),
            preserve_default=False,
        ),
    ]
